config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, logout_then_login
from login.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('erp.urls')),
    path('',LoginFormView.as_view(), name = 'login'),
    path('login/logout/', LogoutView.as_view(next_page='login'), name = 'logout'),
]

erp/urls.py
from unicodedata import name
from django.urls import path
from erp.views import UsuarioView
from django.contrib.auth.decorators import login_required

app_name = 'erp'

urlpatterns = [
    path('<cedula_empleado>', UsuarioView.as_view(), name="obtener_usuario"),
    path('', UsuarioView.as_view(), name="home"),    
]

erp/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.contrib.auth.hashers import make_password
from datetime import datetime

# Create your models here.
class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password):

        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class Usuario(AbstractBaseUser):    
    nombres = models.CharField(max_length=50, verbose_name='Nombres', null=True)
    apellido_uno = models.CharField(max_length=50, verbose_name='Primer Apellido', null=True)
    apellido_dos = models.CharField(max_length=50, verbose_name='Segundo Apellido', null=True)
    cedula= models.CharField(max_length=50, verbose_name='Cedula', null=True)
    fecha_nacimiento = models.DateField(max_length=150, verbose_name='Fecha de nacimiento', null=True)
    genero = models.CharField(max_length=50, verbose_name='Genero', null=True)
    fecha_Ingreso = models.DateField(max_length=150, verbose_name='Fecha de ingreso', null=True)
    numeroempleado = models.CharField(max_length=50, verbose_name='Numero empleado', null=True)
    cargo = models.CharField(max_length=50, verbose_name='Cargo', null=True)
    zona = models.CharField(max_length=50, verbose_name='Zona', null=True)
    municipio = models.CharField(max_length=50, verbose_name='Municipio', null=True)
    departamento = models.CharField(max_length=50, verbose_name='Departamento', null=True)
    ventas_anteriores = models.CharField(max_length=50, verbose_name='Ventas', null=True)
    contraseña = models.CharField(max_length=50, verbose_name='Contraseña', null=True)
    imagen = models.CharField(max_length=50, verbose_name='Imagen', null=True)
    celular = models.CharField(max_length=50, verbose_name='Celular', null=True)
    jefe = models.CharField(max_length=50, null=True)

    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def before_import_row(self,row, **kwargs):
        self.password = row['password']
        row['password'] = make_password(self.password)

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin 

    def __str__(self):
        return self.cedula

    def get_queryset(self):
        pk=self.kwargs['pk']
        if Usuario.objects.filter(id=pk).exists():
            return Usuario.objects.filter(id=pk)

    class Meta:
            verbose_name = 'Usuario'
            verbose_name_plural = 'Usuario' 
            db_table = 'usuario'
            ordering = ['id']

login/models.py
from django.db import models

# Create your models here.

erp/views.py
from pyexpat import model
from tokenize import Double
from django.shortcuts import render
from django.views import View
from erp.models import Usuario
from erp.services import is_show_jefe, is_permission
from erp.services import get_total_sales

# Create your views here.

#Se mandan datos del usuario logueado como sus datos, su jefe y sus subalternos
class UsuarioView(View):    
    def get(self, request, *args, **kwargs):
        if 'cedula_empleado' in kwargs:
            cedula_empleado: int = kwargs['cedula_empleado']
            usuario = Usuario.objects.get(numeroempleado=cedula_empleado)

        else:
            usuario = request.user
        context ={}
        context["usuario"] = usuario
        if context["usuario"].jefe:
            context["jefe"] = Usuario.objects.get(numeroempleado=usuario.jefe)
            context["mostrarjefe"] = is_show_jefe(request.user, context["jefe"])
        # context["subalternos"] = Usuario.objects.filter(jefe=usuario.numeroempleado)
        subalternos = Usuario.objects.filter(jefe=usuario.numeroempleado)


        
        ventas_subalternos = 0   
        for c in subalternos:

                total_subalterno = int(get_total_sales(c.numeroempleado))
                c.total_ventas = total_subalterno
                ventas_subalternos += total_subalterno

        context["subalternos"] = subalternos
        context["ventas_subalternos"] = ventas_subalternos

        return render(request, "../templates/usuario/perfil.html", context)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import FormView
from django.http import HttpResponse
import config.settings as setting
# Create your views here.

class LoginFormView(LoginView):
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(setting.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Iniciar sesión'

        return context

erp/templates/usuario/perfil.html
{% extends 'body.html' %}
{% load static %}

{% block perfil %}

    <div>
        <h3>{{usuario.nombres}} {{usuario.apellido_uno}} {{usuario.apellido_dos}}</h3>
        <h3 class="numEmpleado">{{usuario.numeroempleado}}</h3>
        <br>
            <div class="masinfo">
                    <img src="/static/img/{{usuario.imagen}}" height="">
                <div class="info2">
                    <h4 cla>{{usuario.cargo}}</h4>
                    <br>
                    <h4 cla>{{usuario.zona}}</h4>
                    <br>
                    <h4>{{usuario.municipio}}, {{usuario.departamento}}</h4>
                    <br>

                    {% if usuario.cargo == 'Ejecutivo Comercial' %}
                        <div class="info3">                        
                                <h3>${{usuario.ventas_anteriores}}</h3>                            
                        </div>
                    {% elif subalternos %}                           
                        {% if ventas_subalternos %}                                   
                        <div class="info3"> 
                            <h3>${{ventas_subalternos}}</h3>                                                                                           
                        </div>
                        {% else %}                                       
                        {% endif %}
                    {% else %}                                                
                    {% endif %}
                </div>                
            </div>   
            <br><br>            
            <h4>Teléfono: {{usuario.celular}}</h4>
            <h4>Email: {{usuario.email}}</h4>
            <br>
            <h4>Fecha de Nacimiento: {{usuario.fecha_nacimiento}}</h4>
            <h4>Cédula: {{usuario.cedula}}</h4>
            <br>
            <h4>Fecha de Ingreso: {{usuario.fecha_Ingreso}}</h4>            

            {% if jefe %}
                {% if mostrarjefe %}  
                    <h4>Jefe: <a class="enlacesubalterno" href="{% url 'erp:home' %}{{jefe.numeroempleado}}">{{jefe.nombres}} {{jefe.apellido_uno}}</a></h4>                                                     
                {% else %}    
                    <h4>Jefe: {{jefe.nombres}} {{jefe.apellido_uno}}</h4>     
                {% endif %}                               
            {% else %}
                <h4>Jefe: No tiene</h4>                
            {% endif %}

            <br>

        {% if subalternos %}     
            <h2 class="subalternos">Subalternos</h2>  
            <br>

            <div class="tablasub">
                <table class="table" id="data">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Ventas</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for subalterno in subalternos %}
                                <tr>
                                    <td class="enlacesubalterno">
                                        <a a class="enlacesubalterno" href="{% url 'erp:home' %}{{subalterno.numeroempleado}}">{{subalterno.nombres}} {{subalterno.apellido_uno}}</a>
                                    </td>
                                    <td>$ {{subalterno.total_ventas}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                </table> 
            </div>       
        {% endif %}
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Pagina responsiva">
    <meta name="description" content="Descripcion del sitio">
    <meta name="keywords" content="responsive, html, css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <title>S.U. Logistics</title>
</head>

{% block body %}

{% endblock %}

</html>

templates/body.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<body>

    <div class="contenedor">

        <div class="header">
            {% include 'header.html' %}
        </div>

        <div class="body">

            <nav class="fila">

                <div class="col-lg-4 con-md-4 col-sm-4 col-xs-12">
    
                        <h4 class="tituloperfil">Perfil del usuario</h4>
                        {% block perfil %}
    
                        {% endblock %}
    
                </div>
            </nav>                
        </div>
    </div>

</body>
{% endblock %}

templates/header.html
{% load static %}

{% block header %}

<div class="header2">
    <div class="header1">
        <h1 class="logistics">S.U.Logistics</h1>
    
        <h5 class="logout"><a href="{% url 'logout' %}">Salir</a></h5>
        
    </div>

</div>

{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Pagina responsiva">
    <meta name="description" content="Descripcion del sitio">
    <meta name="keywords" content="responsive, html, css">

    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <title>Iniciar Sesión</title>
</head>

<body>
        <section class="form-login">
            <form method="post" action="{% url 'login' %}">
              {% csrf_token %}                
                <h5 class="h3 mb-3 fw-normal">Iniciar sesión</h5>                   
                
                <input type="text" name="username" class="form-control" placeholder="Nombre de usuario" required="" id="id_username">                  
                
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Contraseña" required="" id="id_password">
                                
                <button class="buttonlogin" type="submit" value="login">Ingresar</button>
                {% if form.errors %}
                <p>Error al iniciar sesión. Por favor, intenta de nuevo.</p>
                {% endif %}
              
            </form>
          </section>
</body>

</html>